# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'muadil.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class bjtmain(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(610, 573)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_deger = QtWidgets.QLabel(self.centralwidget)
        self.label_deger.setGeometry(QtCore.QRect(20, 20, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_deger.setFont(font)
        self.label_deger.setFrameShape(QtWidgets.QFrame.Box)
        self.label_deger.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_deger.setLineWidth(2)
        self.label_deger.setMidLineWidth(1)
        self.label_deger.setObjectName("label_deger")
        self.mat = QtWidgets.QLabel(self.centralwidget)
        self.mat.setGeometry(QtCore.QRect(20, 80, 47, 13))
        self.mat.setObjectName("mat")
        self.yapi = QtWidgets.QLabel(self.centralwidget)
        self.yapi.setGeometry(QtCore.QRect(20, 110, 47, 13))
        self.yapi.setObjectName("yapi")
        self.Pc = QtWidgets.QLabel(self.centralwidget)
        self.Pc.setGeometry(QtCore.QRect(20, 140, 47, 16))
        self.Pc.setObjectName("Pc")
        self.Vcb = QtWidgets.QLabel(self.centralwidget)
        self.Vcb.setGeometry(QtCore.QRect(20, 170, 47, 16))
        self.Vcb.setObjectName("Vcb")
        self.Vce = QtWidgets.QLabel(self.centralwidget)
        self.Vce.setGeometry(QtCore.QRect(20, 200, 47, 16))
        self.Vce.setObjectName("Vce")
        self.Veb = QtWidgets.QLabel(self.centralwidget)
        self.Veb.setGeometry(QtCore.QRect(20, 230, 47, 16))
        self.Veb.setObjectName("Veb")
        self.Ic = QtWidgets.QLabel(self.centralwidget)
        self.Ic.setGeometry(QtCore.QRect(20, 260, 47, 16))
        self.Ic.setObjectName("Ic")
        self.Tj = QtWidgets.QLabel(self.centralwidget)
        self.Tj.setGeometry(QtCore.QRect(20, 290, 47, 21))
        self.Tj.setObjectName("Tj")
        self.Ft = QtWidgets.QLabel(self.centralwidget)
        self.Ft.setGeometry(QtCore.QRect(20, 320, 47, 16))
        self.Ft.setObjectName("Ft")
        self.Cc = QtWidgets.QLabel(self.centralwidget)
        self.Cc.setGeometry(QtCore.QRect(20, 350, 47, 16))
        self.Cc.setObjectName("Cc")
        self.Hfe = QtWidgets.QLabel(self.centralwidget)
        self.Hfe.setGeometry(QtCore.QRect(20, 380, 47, 16))
        self.Hfe.setObjectName("Hfe")
        self.mat_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.mat_txt.setGeometry(QtCore.QRect(80, 80, 101, 20))
        self.mat_txt.setObjectName("mat_txt")
        self.yapi_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.yapi_txt.setGeometry(QtCore.QRect(80, 110, 101, 20))
        self.yapi_txt.setObjectName("yapi_txt")
        self.pc_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.pc_txt.setGeometry(QtCore.QRect(80, 140, 101, 20))
        self.pc_txt.setObjectName("pc_txt")
        self.vcb_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.vcb_txt.setGeometry(QtCore.QRect(80, 170, 101, 20))
        self.vcb_txt.setObjectName("vcb_txt")
        self.vce_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.vce_txt.setGeometry(QtCore.QRect(80, 200, 101, 20))
        self.vce_txt.setObjectName("vce_txt")
        self.veb_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.veb_txt.setGeometry(QtCore.QRect(80, 230, 101, 20))
        self.veb_txt.setObjectName("veb_txt")
        self.ic_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.ic_txt.setGeometry(QtCore.QRect(80, 260, 101, 20))
        self.ic_txt.setObjectName("ic_txt")
        self.tj_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.tj_txt.setGeometry(QtCore.QRect(80, 290, 101, 20))
        self.tj_txt.setObjectName("tj_txt")
        self.ft_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.ft_txt.setGeometry(QtCore.QRect(80, 320, 101, 20))
        self.ft_txt.setObjectName("ft_txt")
        self.cc_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.cc_txt.setGeometry(QtCore.QRect(80, 350, 101, 20))
        self.cc_txt.setObjectName("cc_txt")
        self.hfe_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.hfe_txt.setGeometry(QtCore.QRect(80, 380, 101, 20))
        self.hfe_txt.setObjectName("hfe_txt")
        self.caps_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.caps_txt.setGeometry(QtCore.QRect(80, 410, 101, 20))
        self.caps_txt.setObjectName("caps_txt")
        self.btn_ara = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ara.setGeometry(QtCore.QRect(90, 440, 75, 23))
        self.btn_ara.setObjectName("btn_ara")
        self.label_muadil = QtWidgets.QLabel(self.centralwidget)
        self.label_muadil.setGeometry(QtCore.QRect(330, 20, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_muadil.setFont(font)
        self.label_muadil.setFrameShape(QtWidgets.QFrame.Box)
        self.label_muadil.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_muadil.setLineWidth(2)
        self.label_muadil.setMidLineWidth(1)
        self.label_muadil.setObjectName("label_muadil")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(300, 20, 20, 531))
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Caps = QtWidgets.QLabel(self.centralwidget)
        self.Caps.setGeometry(QtCore.QRect(20, 410, 61, 16))
        self.Caps.setObjectName("Caps")
        self.liste_box = QtWidgets.QListWidget(self.centralwidget)
        self.liste_box.setGeometry(QtCore.QRect(330, 80, 256, 351))
        self.liste_box.setObjectName("liste_box")
        self.btn_tutorial = QtWidgets.QPushButton(self.centralwidget)
        self.btn_tutorial.setGeometry(QtCore.QRect(510, 510, 75, 23))
        self.btn_tutorial.setObjectName("btn_tutorial")
        self.btn_temizle = QtWidgets.QPushButton(self.centralwidget)
        self.btn_temizle.setGeometry(QtCore.QRect(90, 470, 75, 23))
        self.btn_temizle.setObjectName("btn_temizle")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 140, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(190, 170, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(190, 200, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(190, 230, 47, 13))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(190, 260, 47, 13))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(190, 290, 47, 13))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(190, 320, 91, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(190, 350, 71, 16))
        self.label_10.setObjectName("label_10")
        self.txt_adet = QtWidgets.QLabel(self.centralwidget)
        self.txt_adet.setGeometry(QtCore.QRect(330, 440, 181, 21))
        self.txt_adet.setObjectName("txt_adet")
        self.label_sayfa = QtWidgets.QLabel(self.centralwidget)
        self.label_sayfa.setGeometry(QtCore.QRect(330, 480, 47, 13))
        self.label_sayfa.setObjectName("label_sayfa")
        self.syf_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.syf_edit.setGeometry(QtCore.QRect(370, 479, 41, 16))
        self.syf_edit.setObjectName("syf_edit")
        self.btn_geri = QtWidgets.QPushButton(self.centralwidget)
        self.btn_geri.setGeometry(QtCore.QRect(90, 500, 75, 23))
        self.btn_geri.setObjectName("btn_geri")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 610, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Muadil Transistör Bulucu"))
        self.label_deger.setText(_translate("MainWindow", "Lütfen Transistör Değerlerini Giriniz"))
        self.mat.setText(_translate("MainWindow", "Materyal: "))
        self.yapi.setText(_translate("MainWindow", "Yapı: "))
        self.Pc.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">P</span><span style=\" font-size:10pt; vertical-align:sub;\">c</span><span style=\" font-size:10pt;\"> &gt; </span></p></body></html>"))
        self.Vcb.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">V</span><span style=\" font-size:10pt; vertical-align:sub;\">cb</span><span style=\" font-size:10pt;\"> &gt; </span></p></body></html>"))
        self.Vce.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">V</span><span style=\" font-size:10pt; vertical-align:sub;\">ce</span><span style=\" font-size:10pt;\"> &gt;</span></p></body></html>"))
        self.Veb.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">V</span><span style=\" font-size:10pt; vertical-align:sub;\">eb</span><span style=\" font-size:10pt;\"> &gt; </span></p></body></html>"))
        self.Ic.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">I</span><span style=\" font-size:10pt; vertical-align:sub;\">c</span><span style=\" font-size:10pt;\"> &gt;</span></p></body></html>"))
        self.Tj.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">T</span><span style=\" font-size:10pt; vertical-align:sub;\">j</span><span style=\" font-size:10pt;\"> &gt; </span></p></body></html>"))
        self.Ft.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">F</span><span style=\" font-size:10pt; vertical-align:sub;\">t</span><span style=\" font-size:10pt;\"> &gt;</span></p></body></html>"))
        self.Cc.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">C</span><span style=\" font-size:10pt; vertical-align:sub;\">c</span><span style=\" font-size:10pt;\"> &lt;</span></p></body></html>"))
        self.Hfe.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">h</span><span style=\" font-size:10pt; vertical-align:sub;\">FE</span><span style=\" font-size:10pt;\"> &gt;</span></p></body></html>"))
        self.btn_ara.setText(_translate("MainWindow", "Ara"))
        self.label_muadil.setText(_translate("MainWindow", "Muadil Transistör Listesi"))
        self.Caps.setText(_translate("MainWindow", "Paket Türü:"))
        self.btn_tutorial.setText(_translate("MainWindow", "Yardım"))
        self.btn_temizle.setText(_translate("MainWindow", "Temizle"))
        self.label_3.setText(_translate("MainWindow", "W(Watt)"))
        self.label_4.setText(_translate("MainWindow", "V(Volt)"))
        self.label_5.setText(_translate("MainWindow", "V(Volt)"))
        self.label_6.setText(_translate("MainWindow", "V(Volt)"))
        self.label_7.setText(_translate("MainWindow", "A(Amper)"))
        self.label_8.setText(_translate("MainWindow", "C(Celsius)"))
        self.label_9.setText(_translate("MainWindow", "MHz(Mega Hertz)"))
        self.label_10.setText(_translate("MainWindow", "pF(piko Farad)"))
        self.txt_adet.setText(_translate("MainWindow", "Adet: "))
        self.label_sayfa.setText(_translate("MainWindow", "Sayfa:"))
        self.syf_edit.setText(_translate("MainWindow", "1"))
        self.btn_geri.setText(_translate("MainWindow", "Geri"))


