# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'igbt_main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class igbtmain(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(610, 573)
        self.btn_ara = QtWidgets.QPushButton(Form)
        self.btn_ara.setGeometry(QtCore.QRect(90, 400, 75, 23))
        self.btn_ara.setObjectName("btn_ara")
        self.btn_temizle = QtWidgets.QPushButton(Form)
        self.btn_temizle.setGeometry(QtCore.QRect(90, 430, 75, 23))
        self.btn_temizle.setObjectName("btn_temizle")
        self.btn_geri = QtWidgets.QPushButton(Form)
        self.btn_geri.setGeometry(QtCore.QRect(90, 460, 75, 23))
        self.btn_geri.setObjectName("btn_geri")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(300, 20, 20, 531))
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 110, 47, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 200, 47, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 47, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 230, 47, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 290, 47, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(20, 170, 47, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(20, 260, 47, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(20, 320, 47, 16))
        self.label_8.setObjectName("label_8")
        self.txt_yapi = QtWidgets.QLineEdit(Form)
        self.txt_yapi.setGeometry(QtCore.QRect(80, 80, 101, 20))
        self.txt_yapi.setObjectName("txt_yapi")
        self.txt_pc = QtWidgets.QLineEdit(Form)
        self.txt_pc.setGeometry(QtCore.QRect(80, 110, 101, 20))
        self.txt_pc.setObjectName("txt_pc")
        self.txt_vce = QtWidgets.QLineEdit(Form)
        self.txt_vce.setGeometry(QtCore.QRect(80, 140, 101, 20))
        self.txt_vce.setObjectName("txt_vce")
        self.txt_vcesat = QtWidgets.QLineEdit(Form)
        self.txt_vcesat.setGeometry(QtCore.QRect(80, 170, 101, 20))
        self.txt_vcesat.setObjectName("txt_vcesat")
        self.txt_veg = QtWidgets.QLineEdit(Form)
        self.txt_veg.setGeometry(QtCore.QRect(80, 200, 101, 20))
        self.txt_veg.setObjectName("txt_veg")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(20, 80, 47, 16))
        self.label_9.setObjectName("label_9")
        self.txt_ic = QtWidgets.QLineEdit(Form)
        self.txt_ic.setGeometry(QtCore.QRect(80, 230, 101, 20))
        self.txt_ic.setObjectName("txt_ic")
        self.txt_tj = QtWidgets.QLineEdit(Form)
        self.txt_tj.setGeometry(QtCore.QRect(80, 260, 101, 20))
        self.txt_tj.setObjectName("txt_tj")
       
        
        
        self.txt_tr = QtWidgets.QLineEdit(Form)
        self.txt_tr.setGeometry(QtCore.QRect(80, 290, 101, 20))
        self.txt_tr.setObjectName("txt_tr")
        self.txt_cc = QtWidgets.QLineEdit(Form)
        self.txt_cc.setGeometry(QtCore.QRect(80, 320, 101, 20))
        self.txt_cc.setObjectName("txt_cc")
        self.txt_paket = QtWidgets.QLineEdit(Form)
        self.txt_paket.setGeometry(QtCore.QRect(80, 350, 101, 20))
        self.txt_paket.setObjectName("txt_paket")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(190, 110, 47, 13))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(190, 140, 47, 13))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(190, 170, 47, 13))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(190, 200, 47, 13))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(190, 230, 47, 13))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(190, 260, 47, 13))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(190, 290, 75, 13))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(190, 320, 75, 13))
        self.label_18.setObjectName("label_18")
        self.btn_tutorial = QtWidgets.QPushButton(Form)
        self.btn_tutorial.setGeometry(QtCore.QRect(510, 510, 75, 23))
        self.btn_tutorial.setObjectName("btn_tutorial")
        self.lbl_adet = QtWidgets.QLabel(Form)
        self.lbl_adet.setGeometry(QtCore.QRect(330, 440, 131, 21))
        self.lbl_adet.setObjectName("lbl_adet")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(330, 480, 47, 13))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(20, 350, 55, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(330, 20, 271, 41))
        self.label_21.setFrameShape(QtWidgets.QFrame.Box)
        self.label_21.setLineWidth(2)
        self.label_21.setMidLineWidth(1)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(20, 20, 271, 41))
        self.label_22.setFrameShape(QtWidgets.QFrame.Box)
        self.label_22.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_22.setLineWidth(2)
        self.label_22.setMidLineWidth(1)
        self.label_22.setTextFormat(QtCore.Qt.AutoText)
        self.label_22.setObjectName("label_22")
        self.liste2 = QtWidgets.QListWidget(Form)
        self.liste2.setGeometry(QtCore.QRect(330, 80, 256, 351))
        self.liste2.setObjectName("liste2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Muadil Transistör Bulucu"))
        self.btn_ara.setText(_translate("Form", "Ara"))
        self.btn_temizle.setText(_translate("Form", "Temizle"))
        self.btn_geri.setText(_translate("Form", "Geri"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">P</span><span style=\" font-size:10pt; vertical-align:sub;\">c</span><span style=\" font-size:10pt;\"> &gt;</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">V</span><span style=\" font-size:10pt; vertical-align:sub;\">EG</span><span style=\" font-size:10pt;\"> &gt;</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">V</span><span style=\" font-size:10pt; vertical-align:sub;\">CE</span><span style=\" font-size:10pt;\"> &gt;</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">I</span><span style=\" font-size:10pt; vertical-align:sub;\">c</span><span style=\" font-size:10pt;\"> &gt;</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">t</span><span style=\" font-size:10pt; vertical-align:sub;\">r</span><span style=\" font-size:10pt;\"> &lt;</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">V</span><span style=\" font-size:10pt; vertical-align:sub;\">CE  </span>sat<span style=\" font-size:10pt;\"> &lt;</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">T</span><span style=\" font-size:10pt; vertical-align:sub;\">j</span><span style=\" font-size:10pt;\"> &gt;</span></p></body></html>"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">C</span><span style=\" font-size:10pt; vertical-align:sub;\">C</span><span style=\" font-size:10pt;\"> &gt;</span></p></body></html>"))
        self.label_9.setText(_translate("Form", "Yapı:"))
        self.label_11.setText(_translate("Form", "W(Watt)"))
        self.label_12.setText(_translate("Form", "V(Volt)"))
        self.label_13.setText(_translate("Form", "V(Volt)"))
        self.label_14.setText(_translate("Form", "V(Volt)"))
        self.label_15.setText(_translate("Form", "A(Amper)"))
        self.label_16.setText(_translate("Form", "C(Celsius)"))
        self.label_17.setText(_translate("Form", "ns(Nanosaniye)"))
        self.label_18.setText(_translate("Form", "pF(Pikofarad)"))
        self.btn_tutorial.setText(_translate("Form", "Yardım"))
        self.lbl_adet.setText(_translate("Form", "Adet:"))
        self.label_20.setText(_translate("Form", "Paket Türü:"))
        self.label_21.setText(_translate("Form", "<html><head/><body><p><span style=\" font-family:\'Times New Roman,serif\'; font-size:12pt; font-weight:600; font-style:italic;\">Muadil Transistör Listesi</span></p></body></html>"))
        self.label_22.setText(_translate("Form", "<html><head/><body><p><span style=\" font-family:\'Times New Roman,serif\'; font-size:12pt; font-weight:600; font-style:italic;\">Lütfen Transistör Değerini Giriniz</span></p></body></html>"))


