# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mosfet_main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class mosfetmain(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(610, 573)
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(300, 20, 20, 531))
        self.line.setMidLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_LutfenTransistorDegeriniGiriniz = QtWidgets.QLabel(Form)
        self.label_LutfenTransistorDegeriniGiriniz.setGeometry(QtCore.QRect(20, 20, 271, 41))
        self.label_LutfenTransistorDegeriniGiriniz.setFrameShape(QtWidgets.QFrame.Box)
        self.label_LutfenTransistorDegeriniGiriniz.setLineWidth(2)
        self.label_LutfenTransistorDegeriniGiriniz.setMidLineWidth(1)
        self.label_LutfenTransistorDegeriniGiriniz.setObjectName("label_LutfenTransistorDegeriniGiriniz")
        self.label_MuadilTransistorListesi = QtWidgets.QLabel(Form)
        self.label_MuadilTransistorListesi.setGeometry(QtCore.QRect(330, 20, 271, 41))
        self.label_MuadilTransistorListesi.setFrameShape(QtWidgets.QFrame.Box)
        self.label_MuadilTransistorListesi.setLineWidth(2)
        self.label_MuadilTransistorListesi.setMidLineWidth(1)
        self.label_MuadilTransistorListesi.setObjectName("label_MuadilTransistorListesi")
        self.label_Yapi = QtWidgets.QLabel(Form)
        self.label_Yapi.setGeometry(QtCore.QRect(20, 80, 47, 16))
        self.label_Yapi.setObjectName("label_Yapi")
        self.label_Pd = QtWidgets.QLabel(Form)
        self.label_Pd.setGeometry(QtCore.QRect(20, 140, 47, 16))
        self.label_Pd.setObjectName("label_Pd")
        self.label_Vgs = QtWidgets.QLabel(Form)
        self.label_Vgs.setGeometry(QtCore.QRect(20, 200, 47, 16))
        self.label_Vgs.setObjectName("label_Vgs")
        self.label_Id = QtWidgets.QLabel(Form)
        self.label_Id.setGeometry(QtCore.QRect(20, 260, 47, 16))
        self.label_Id.setObjectName("label_Id")
        self.label_tr = QtWidgets.QLabel(Form)
        self.label_tr.setGeometry(QtCore.QRect(20, 350, 47, 16))
        self.label_tr.setObjectName("label_tr")
        self.label_Cd = QtWidgets.QLabel(Form)
        self.label_Cd.setGeometry(QtCore.QRect(20, 380, 47, 16))
        self.label_Cd.setObjectName("label_Cd")
        self.label_Tj = QtWidgets.QLabel(Form)
        self.label_Tj.setGeometry(QtCore.QRect(20, 290, 47, 21))
        self.label_Tj.setObjectName("label_Tj")
        self.label_Vds = QtWidgets.QLabel(Form)
        self.label_Vds.setGeometry(QtCore.QRect(20, 170, 47, 16))
        self.label_Vds.setObjectName("label_Vds")
        self.label_Polarite = QtWidgets.QLabel(Form)
        self.label_Polarite.setGeometry(QtCore.QRect(20, 110, 47, 16))
        self.label_Polarite.setObjectName("label_Polarite")
        self.label_Qg = QtWidgets.QLabel(Form)
        self.label_Qg.setGeometry(QtCore.QRect(20, 320, 47, 16))
        self.label_Qg.setObjectName("label_Qg")
        self.label_Rds = QtWidgets.QLabel(Form)
        self.label_Rds.setGeometry(QtCore.QRect(20, 410, 47, 16))
        self.label_Rds.setObjectName("label_Rds")
        self.label_PaketTuru = QtWidgets.QLabel(Form)
        self.label_PaketTuru.setGeometry(QtCore.QRect(20, 440, 55, 16))
        self.label_PaketTuru.setObjectName("label_PaketTuru")
        self.label_Vgsth = QtWidgets.QLabel(Form)
        self.label_Vgsth.setGeometry(QtCore.QRect(20, 230, 47, 16))
        self.label_Vgsth.setObjectName("label_Vgsth")
        self.linePolarite_2 = QtWidgets.QLineEdit(Form)
        self.linePolarite_2.setGeometry(QtCore.QRect(80, 110, 101, 20))
        self.linePolarite_2.setObjectName("linePolarite_2")
        self.linePd_3 = QtWidgets.QLineEdit(Form)
        self.linePd_3.setGeometry(QtCore.QRect(80, 140, 101, 20))
        self.linePd_3.setObjectName("linePd_3")
        self.lineVds_4 = QtWidgets.QLineEdit(Form)
        self.lineVds_4.setGeometry(QtCore.QRect(80, 170, 101, 20))
        self.lineVds_4.setObjectName("lineVds_4")
        self.lineVgs_5 = QtWidgets.QLineEdit(Form)
        self.lineVgs_5.setGeometry(QtCore.QRect(80, 200, 101, 20))
        self.lineVgs_5.setObjectName("lineVgs_5")
        self.lineVgsth_6 = QtWidgets.QLineEdit(Form)
        self.lineVgsth_6.setGeometry(QtCore.QRect(80, 230, 101, 20))
        self.lineVgsth_6.setObjectName("lineVgsth_6")
        self.lineId_7 = QtWidgets.QLineEdit(Form)
        self.lineId_7.setGeometry(QtCore.QRect(80, 260, 101, 20))
        self.lineId_7.setObjectName("lineId_7")
        self.lineTj_8 = QtWidgets.QLineEdit(Form)
        self.lineTj_8.setGeometry(QtCore.QRect(80, 290, 101, 20))
        self.lineTj_8.setObjectName("lineTj_8")
        self.lineQg_9 = QtWidgets.QLineEdit(Form)
        self.lineQg_9.setGeometry(QtCore.QRect(80, 320, 101, 20))
        self.lineQg_9.setObjectName("lineQg_9")
        self.linetr_10 = QtWidgets.QLineEdit(Form)
        self.linetr_10.setGeometry(QtCore.QRect(80, 350, 101, 20))
        self.linetr_10.setObjectName("linetr_10")
        self.lineCd_11 = QtWidgets.QLineEdit(Form)
        self.lineCd_11.setGeometry(QtCore.QRect(80, 380, 101, 20))
        self.lineCd_11.setObjectName("lineCd_11")
        self.lineRds_12 = QtWidgets.QLineEdit(Form)
        self.lineRds_12.setGeometry(QtCore.QRect(80, 410, 101, 20))
        self.lineRds_12.setObjectName("lineRds_12")
        self.line_PaketTuru_13 = QtWidgets.QLineEdit(Form)
        self.line_PaketTuru_13.setGeometry(QtCore.QRect(80, 440, 101, 20))
        self.line_PaketTuru_13.setObjectName("line_PaketTuru_13")
        self.label_nS = QtWidgets.QLabel(Form)
        self.label_nS.setGeometry(QtCore.QRect(190, 350, 75, 13))
        self.label_nS.setObjectName("label_nS")
        self.label_W = QtWidgets.QLabel(Form)
        self.label_W.setGeometry(QtCore.QRect(190, 140, 47, 13))
        self.label_W.setObjectName("label_W")
        self.label_V1 = QtWidgets.QLabel(Form)
        self.label_V1.setGeometry(QtCore.QRect(190, 170, 47, 13))
        self.label_V1.setObjectName("label_V1")
        self.label_V2 = QtWidgets.QLabel(Form)
        self.label_V2.setGeometry(QtCore.QRect(190, 200, 47, 13))
        self.label_V2.setObjectName("label_V2")
        self.label_V3 = QtWidgets.QLabel(Form)
        self.label_V3.setGeometry(QtCore.QRect(190, 230, 47, 13))
        self.label_V3.setObjectName("label_V3")
        self.label_A = QtWidgets.QLabel(Form)
        self.label_A.setGeometry(QtCore.QRect(190, 260, 47, 13))
        self.label_A.setObjectName("label_A")
        self.label_C = QtWidgets.QLabel(Form)
        self.label_C.setGeometry(QtCore.QRect(190, 290, 47, 13))
        self.label_C.setObjectName("label_C")
        self.label_nC = QtWidgets.QLabel(Form)
        self.label_nC.setGeometry(QtCore.QRect(190, 320, 85, 13))
        self.label_nC.setObjectName("label_nC")
        self.label_pF = QtWidgets.QLabel(Form)
        self.label_pF.setGeometry(QtCore.QRect(190, 380, 75, 13))
        self.label_pF.setObjectName("label_pF")
        self.label_Ohm = QtWidgets.QLabel(Form)
        self.label_Ohm.setGeometry(QtCore.QRect(190, 410, 47, 13))
        self.label_Ohm.setObjectName("label_Ohm")
        self.btn_ara = QtWidgets.QPushButton(Form)
        self.btn_ara.setGeometry(QtCore.QRect(90, 470, 75, 23))
        self.btn_ara.setObjectName("btn_ara")
        self.btn_temizle = QtWidgets.QPushButton(Form)
        self.btn_temizle.setGeometry(QtCore.QRect(90, 500, 75, 23))
        self.btn_temizle.setObjectName("btn_temizle")
        self.btn_geri = QtWidgets.QPushButton(Form)
        self.btn_geri.setGeometry(QtCore.QRect(90, 530, 75, 23))
        self.btn_geri.setObjectName("btn_geri")
        self.btn_yardim = QtWidgets.QPushButton(Form)
        self.btn_yardim.setGeometry(QtCore.QRect(510, 510, 75, 23))
        self.btn_yardim.setObjectName("btn_yardim")
        self.label_Adet = QtWidgets.QLabel(Form)
        self.label_Adet.setGeometry(QtCore.QRect(330, 440, 141, 31))
        self.label_Adet.setObjectName("label_Adet")
        self.liste3 = QtWidgets.QListWidget(Form)
        self.liste3.setGeometry(QtCore.QRect(330, 70, 256, 361))
        self.liste3.setObjectName("liste3")
        self.yapibox = QtWidgets.QComboBox(Form)
        self.yapibox.setGeometry(QtCore.QRect(80, 80, 101, 22))
        self.yapibox.setObjectName("yapibox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Muadil Transistör Bulucu"))
        self.label_LutfenTransistorDegeriniGiriniz.setText(_translate("Form", "<html><head/><body><p><span style=\" font-family:\'Times New Roman,serif\'; font-size:12pt; font-weight:600; font-style:italic;\">Lütfen Transistör Değerini Giriniz</span></p></body></html>"))
        self.label_MuadilTransistorListesi.setText(_translate("Form", "<html><head/><body><p><span style=\" font-family:\'Times New Roman,serif\'; font-size:12pt; font-weight:600; font-style:italic;\">Muadil Transistör Listesi</span></p></body></html>"))
        self.label_Yapi.setText(_translate("Form", "Yapı:"))
        self.label_Pd.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">P</span><span style=\" font-size:10pt; vertical-align:sub;\">D</span><span style=\" font-size:10pt;\"> &gt;</span></p></body></html>"))
        self.label_Vgs.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">V</span><span style=\" font-size:10pt; vertical-align:sub;\">GS</span><span style=\" font-size:10pt;\"> &gt;</span></p></body></html>"))
        self.label_Id.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">I</span><span style=\" font-size:10pt; vertical-align:sub;\">D</span><span style=\" font-size:10pt;\"> &gt;</span></p></body></html>"))
        self.label_tr.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">t</span><span style=\" font-size:10pt; vertical-align:sub;\">R</span><span style=\" font-size:10pt;\"> &lt;</span></p></body></html>"))
        self.label_Cd.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">C</span><span style=\" font-size:10pt; vertical-align:sub;\">D</span><span style=\" font-size:10pt;\"> &lt;</span></p></body></html>"))
        self.label_Tj.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">T</span><span style=\" font-size:10pt; vertical-align:sub;\">j</span><span style=\" font-size:10pt;\"> &gt;</span></p></body></html>"))
        self.label_Vds.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">V</span><span style=\" font-size:10pt; vertical-align:sub;\">DS</span><span style=\" font-size:10pt;\"> &gt;</span></p></body></html>"))
        self.label_Polarite.setText(_translate("Form", "Polarite:"))
        self.label_Qg.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Q</span><span style=\" font-size:10pt; vertical-align:sub;\">G </span><span style=\" font-size:10pt;\">&lt;</span></p></body></html>"))
        self.label_Rds.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">R</span><span style=\" font-size:10pt; vertical-align:sub;\">DS</span><span style=\" font-size:10pt;\"> &lt;</span></p></body></html>"))
        self.label_PaketTuru.setText(_translate("Form", "Paket Türü:"))
        self.label_Vgsth.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">V</span><span style=\" font-size:10pt; vertical-align:sub;\">GS</span><span style=\" font-size:10pt;\">(th) &lt;</span></p></body></html>"))
        self.label_nS.setText(_translate("Form", "nS(Nanosaniye)"))
        self.label_W.setText(_translate("Form", "W(Watt)"))
        self.label_V1.setText(_translate("Form", "V(Volt)"))
        self.label_V2.setText(_translate("Form", "V(Volt)"))
        self.label_V3.setText(_translate("Form", "V(Volt)"))
        self.label_A.setText(_translate("Form", "A(Amper)"))
        self.label_C.setText(_translate("Form", "C(Celsius)"))
        self.label_nC.setText(_translate("Form", "nC(Nanocoulomb)"))
        self.label_pF.setText(_translate("Form", "pF(Pikofarad)"))
        self.label_Ohm.setText(_translate("Form", "Ohm"))
        self.btn_ara.setText(_translate("Form", "Ara"))
        self.btn_temizle.setText(_translate("Form", "Temizle"))
        self.btn_geri.setText(_translate("Form", "Geri"))
        self.btn_yardim.setText(_translate("Form", "Yardım"))
        self.label_Adet.setText(_translate("Form", "Adet:"))


